version: "3"
services:
    frontend:
        container_name: cfy_client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: aneeshmelkot/cfy_client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: cfy_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: aneeshmelkot/cfy_server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app